# Site
repository: https://github.com/AdamLee321/adamlee321.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Adam Lee
title: Senior Mobile & Web Developer
email: adam123dublin@gmail.com
github: https://github.com/AdamLee321
linkedIn: https://www.linkedin.com/in/adam-lee-b426668b/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  AdamLee321
stackoverflow_username: "4777072"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: adam_k_lee_
linkedin_username: adam-lee-b426668b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  
  Greetings, travelers of Middle-earth! I am Adam, a seasoned wizard of the digital realm, here to regale you with tales of my adventures as a senior mobile & web developer! ğŸ§™â€â™‚ï¸ğŸ’»

  For a decade now, I've been casting spells in the mystical lands of mobile apps, akin to mastering the arcane arts of the elven smiths. And lo, for a full decade and more, I've treaded the paths of the web, much like the resilient dwarves delving deep into the heart of the mountains! âš”ï¸ğŸ’¼

  In my time as a digital voyager, I've embarked on over 60 epic quests, each one a saga worthy of the bards' songs! Many of these quests have found their way into the halls of Valinor, gracing the Apple and Android app stores with their presence! ğŸ“±ğŸŒŒ

  But fear not, for I am not merely a solitary wanderer. Nay, I have braved the perils of teamwork, standing shoulder to shoulder with brave comrades, just like the Fellowship on their journey to Mordor. And when the path has led me to solitary shores, I've faced the challenges alone, much like Frodo on his solemn quest to destroy the One Ring. ğŸŒ‹ğŸ’

  So, whether I'm marching alongside allies or venturing forth on my own, you can trust in my prowess to craft digital wonders that rival the majesty of Middle-earth itself! ğŸŒŸâœ¨

  My most esteemed qualities: <mark>React Native</mark>, <mark>ReactJS</mark>, <mark>Swift</mark>, <mark>Kotlin</mark>, <mark>Java</mark>, <mark>C#</mark> and <mark>SQL</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: xyz
        link: https://www.site.xyz/
        # link_text: Project Website
        additional_links:
          - title:  Mosaic
            icon: images/mosaic-wheel.png
            url: https://mosaic.ie/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         White-Label Website Infrastructure
        description: | # this will include new lines to allow paragraphs
          From Creative Agencies building multiple Promo websites at speed... to Payment Companies offering eCommerce websites to their merchants under their own brand, we provide you with cutting-edge White-Label Website Infrastructure.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mosaic LTD
        link: https://mosaic.ie/
        # link_text: boringcompany.com
        sub_title: Senior Mobile & Web Developer
        caption: April 2018 - Present
        quote: >
          We thrive on exceeding our client's expectations. We utilise the latest technologies and trends to develop cutting edge Mobile Apps and premium Web Platforms... that WOW our client's customers.
        description: | # this will include new lines to allow paragraphs
            Designing and developing Android & iOS applications for our clients. ReactJS and React Native or other languages used for development.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Altanic Technological University
        caption: 2013 - 2018
        sub_title: BSc Computer Science
        quote: >
          We are one of Irelandâ€™s leading third level institutions for over 50 years and a great destination to get a high quality education.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software development  some of my other interests and hobbies are:
      - Big J.R.R Tolkien fan (As you can see)
      - Gaming
      - DIY
      - Cooking & Baking
      - Travelling

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
